version: '2'
services:
    msufpregister-app:
        image: msufpregister
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://msufpregister-mysql:3306/msufpregister?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    msufpregister-mysql:
        extends:
            file: mysql.yml
            service: msufpregister-mysql
